### ISSUE TITLE
Windows 10 Style Win+Tab Desktop Switcher

### ISSUE THREAD

**Issue by abhigyan2001** [valinet/ExplorerPatcher-L10N#74]
The Windows 11 Task View Desktop Switcher (Win+Tab) is quite slow and laggy to open and to switch to other desktops, and the Windows 10 Task View used to work like a dream.

Would it be possible to update the Task View to use the old Windows 10 Style Task View, where the desktops are displayed at the top and the open applications are all shown below that?

**Comment by abhigyan2001** [comment]
Sorry, wrong repo, I have posted on the ExplorerPatcher repo issues.

**Comment by Amrsatrio** [comment]
No, the code is gone. It is not possible without a terious reimplementation.
