### ISSUE TITLE
No Windows 10 start menu style after updating

### ISSUE THREAD

**Issue by orchestrascores** [valinet/ExplorerPatcher-L10N#81]
Hi, I just updated my computer, after that I noticed the start menu only shows Windows 11. I updated the symbols, still nothing. The program is missing "Start menu style" from Start menu. Please fix this. Thank you!
![Screenshot 2024-08-28 103620](https://github.com/user-attachments/assets/95eb0b28-9335-493e-8a0a-de267c6dda07)

![Screenshot 2024-08-28 103200](https://github.com/user-attachments/assets/c9bafaca-47dc-47b8-8239-afba925c2812)

**Comment by Amrsatrio** [comment]
Not the correct repository to report such issues

To answer your question: Please get EP 66.4 prerelease through the main ExplorerPatcher repo and then going to the Releases section.
